version: '3.8'

services:
  automq:
    image: automqinc/automq:1.6.0
    container_name: automq-single-server
    ports:
      - "9092:9092"
      - "9093:9093"   # Optional for controller communication
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LOG_DIRS: /tmp/kafka-logs
    volumes:
      - ./data:/tmp/kafka-logs
